[mypy]
strict = True
disallow_any_unimported = True
disallow_any_expr = False
disallow_any_explicit = False
disallow_any_generics = True
disallow_subclassing_any = True
disallow_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_return_any = True
warn_unreachable = True
# This merely reflects behavior prior to the introduction of mypy. This should be shortened with urgency, then applied
# on a per-module basis, and then eliminated.
disable_error_code =
    no-untyped-call,
    no-untyped-def,
    union-attr,
    attr-defined,
    type-arg,
    index,
    arg-type,
    no-any-return,
    assignment,
    typeddict-item,
    override,
    var-annotated,
    return-value,
    misc,
    import-untyped,
    operator,
    unreachable,
    has-type,
    call-overload,
    return,
    dict-item,
    valid-type,
    comparison-overlap,
    unused-coroutine,
    type-var,
    str-bytes-safe,
    name-defined,
    typeddict-unknown-key,
    no-redef,
    import-not-found,
    call-arg,
    unused-ignore,
