CRAWL_DATABASE_IP = "192.168.1.11"
MAIN_DATABASE_IP = "192.168.1.54"

DATABASE_PORT = 27017
DATABASE_NAME = "juriscraper"

TEST_COLLECTION = "test"
MAIN_COLLECTION = "JuriscraperData"
CONFIG_COLLECTION = "JuriscrapperCrawlConfig"
