name: Check release notes

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGES.md
