name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: "pyrefly" # This will be handled by a job of its own.

  static-analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      - name: Install uv # this is for the benefit of pyrefly, which is invoked locally, by pre-commit.
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          version: "0.9.x"
      - name: Install dependencies # eager synchronization keeps the output of subsequent `uv` usage by pre-commit clean.
        run: uv sync
      - name: pyrefly Static Type Checker
        run: uv run pyrefly check --output-format full-text-with-github
